name: test-formulas

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test-formulas:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Brew version output
        run: brew --version
      #- name: Brew install bats
      #  run: brew install bats-core
      - name: Install support
        run: brew install --build-from-source --verbose Formula/bats-support.rb
